[package]
name = "onetun"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boringtun = { git = "https://github.com/aramperes/boringtun.git", branch = "onetun" }
clap = { version = "2.33", default-features = false, features = ["suggestions"] }
log = "0.4"
pretty_env_logger = "0.3"
anyhow = "1"
smoltcp = "0.7.5"
packet = "0.1.4"
